<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Province;
use App\Models\City;

class RegionalSeeder extends Seeder
{
    /**
     * Indonesia Province and Cities
     *
     * @return void
     */
    public function run()
    {
        //
        $province = Province::create(['province_name'=>'Aceh']);
	        City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Aceh Barat ']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kota Banda Aceh']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Aceh Barat Daya']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kota Subulussalam']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Aceh Besar']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kota Langsa']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Aceh Jaya']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kota Lhokseumawe']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Aceh Selatan']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kota Saban']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Aceh Singkil']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab Aceh Tamiang']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Aceh Tengah']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Aceh Tenggara']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Aceh Timur']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Aceh Utara']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Bener Meriah']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Bireun']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Gayo Lues']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Nagan Raya']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Pidie']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Pidie Jaya']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Simeulue']);
        $province = Province::create(['province_name'=>'Sumatera Utara']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Asahan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Medan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Batubara']); 
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Binjai']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Dairi']); 
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Padang Sidempuan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Deliserdang']); 
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Pematan Siantar']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Humban Hasundutan']); 
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Sibolga']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Karo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Tanjung Balai']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Labuhanbatu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota TebingTinggi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Langkat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Gunung Sitoli']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Mandating Natal']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Nias']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Nias Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. PakakBharat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Samosir']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Serdan Bedagai']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Simalungun']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tapanuli Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tapanuli Tengah']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tapanuli Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Toba Samosir']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Padang Lawas Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Padan Lawas']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Labuhanbatu Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Labuhanbatu Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Nias Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Nias Utara']);
        $province = Province::create(['province_name'=>'Sumatera Barat']);
        	City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Agam ']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kota Padang']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Dharmasraya ']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kota BukitTinggi']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Limapuluhkota ']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kota Pandang Panjang']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Kep. Mentawai ']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kota Pariaman']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Padang Pariaman ']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kota Payakumbuh']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Pasaman ']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kota Sawahlunto']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Pasaman Barat ']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kota Solok']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Pesisir Selatan']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Sawahlunto Sijunjung']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Solok']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Solok Selatan']);
			City::create(['province_id'=>$province->id,'cities_name'=>'Kab. Tanah Datar']);
        $province = Province::create(['province_name'=>'Riau']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bengkalis']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Pekanbaru']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Indragiri Hilir']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Dumai']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Indragiri Hulu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kampar']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kuantan Singingi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pelalawan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Rokan Hulu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Rokan Hilir']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Siak']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kep. Meranti']);
        $province = Province::create(['province_name'=>'Kepulauan Riau']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Karimun']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Tanjungpinang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bintan (Kep. Riau)']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Batam']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lingga']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Natuna']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kep. Anambas']);
        $province = Province::create(['province_name'=>'Jambi']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Batanghari']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Jambi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bungo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Sungai Penuh']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kerinci']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Merangin']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Muaro Jambi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sarolangun']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tanjung Jabung Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tanjung Jabung Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tebo']);
        $province = Province::create(['province_name'=>'Bengkulu']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bengkulu Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Bengkulu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bengkulu Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kaur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kepahiang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lebong']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Muko-Muko']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Rejang Lebong']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Seluma']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bengkulu Tengah']);
        $province = Province::create(['province_name'=>'Sumatera Selatan']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Banyuasin']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Palembang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lahat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Lubuk Linggau']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Empat Lawang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Pagar Alam']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Muara Enim']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Prabumulih']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Musi Banyuasin']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Musi Rawas']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Ogan Ilir']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Ogan Komering Ilir']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Ogan Komering Ulu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. OKU Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. OKU Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Penukal Abab Lematang Ilir']);
        $province = Province::create(['province_name'=>'Kepulauan Bangka Belitung']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bangka']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Pangkalpinang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bangka Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bangka Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bangka Tengah']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Belitung']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Belitung Timur']);
        $province = Province::create(['province_name'=>'Lampung']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lampung Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Bandarlampung']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lampung Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Metro']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lampung Tengah']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lampung Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lampung Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tanggamus']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tulang Bawang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Way Kanan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pesawaran']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pringsewu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Mesuji']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tulang Bawang Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pesisir Barat']);
        $province = Province::create(['province_name'=>'Banten']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lebak']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Cilegon']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pandeglang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Serang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Serang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Tangerang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tangerang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Tangerang Selatan']);
        $province = Province::create(['province_name'=>'Jawa Barat']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bandung']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Bandung']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bandung Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Banjar']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bekasi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Bekasi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bogor']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Bogor']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Ciamis']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Cimahi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Cianjur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Cirebon']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Cirebon']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Depok']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Garut']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Sukabumi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Indramayu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Tasikmalaya']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Karawang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kuningan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Majalengka']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Purwakarta']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Subang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sukabumi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sumedang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tasikmalaya']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pangandaran']);
        $province = Province::create(['province_name'=>'DKI Jakarta']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kepulauan Seribu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Jakarta Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Jakarta Pusat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Jakarta Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Jakarta Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Jakarta Utara']);
        $province = Province::create(['province_name'=>'Jawa Tengah']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Banjarnegara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Semarang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Banyumas']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Magelang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Batang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Pekalongan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Blora']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Salatiga']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Boyolali']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Surakarta']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Brebes']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Tegal']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Cilacap']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Demak']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Grobogan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Jepara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Karanganyar']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kebumen']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kendal']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Klaten']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kudus']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Magelang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pati']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pekalongan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pemalang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Purbalingga']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Purworejo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Rembang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Semarang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sragen']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sukoharjo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tegal']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Temanggung']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Wonogiri']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Wonosobo']);
        $province = Province::create(['province_name'=>'Jawa Timur']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bangkalan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Surabaya']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Banyuwangi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Batu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Blitar']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Blitar']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bojonegoro']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Kediri']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bondowoso']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Madiun']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Gresik']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Malang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Jember']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Mojokerto']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Jombang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Pasuruan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kediri']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Probolinggo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lamongan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lumajang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Madiun']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Magetan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Malang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Mojokerto']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Nganjuk']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Ngawi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pacitan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pamekasan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pasuruan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Ponorogo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Probolinggo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sampang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sidoarjo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Situbondo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sumenep']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Trenggalek']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tulungagung']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tuban']);
        $province = Province::create(['province_name'=>'Yogyakarta']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bantul']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Yogyakarta']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Gunung Kidul']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kulon Progo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sleman']);
        $province = Province::create(['province_name'=>'Bali']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Badung']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Denpasar']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bangli']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Buleleng']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Gianyar']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Jembrana']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Karang Asem']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Klungkung']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tabanan']);
        $province = Province::create(['province_name'=>'Nusa Tenggara Barat']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bima']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Mataram']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Dompu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Bima']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lombok Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lombok Tengah']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lombok Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sumbawa']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sumbawa Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lombok Utara']);
        $province = Province::create(['province_name'=>'Nusa Tenggara Timur']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Alor']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Kupang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Belu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Ende']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Flores Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kupang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lembata']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Manggarai']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Manggarai Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Ngada']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Nagekeo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Rote Ndao']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Slkka']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sumba Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sumba Barat Daya']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sumba Tengah']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Manggarai Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sumba Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Timor Tengah Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Timor Tengah Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sabu Raijua']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Malaka']);
        $province = Province::create(['province_name'=>'Kalimantan Barat']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bengkayang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Pontianak']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kapuas Hulu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Singkawang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Ketapang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kayong Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kubu Raya']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Landak']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Melawi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pontianak']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sambas']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sanggau']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sintang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sekadau']);
        $province = Province::create(['province_name'=>'Kalimantan Timur']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Berau']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Samarinda']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bulungan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Balikpapan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kutai Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Bontang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kutai Kertanegara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Tarakan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kutai Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Penajam Paser Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pasir']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Mahakam Ulu']);
        $province = Province::create(['province_name'=>'Kalimantan Utara']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab Malinau']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Nunukan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tana Tidung']);
        $province = Province::create(['province_name'=>'Kalimantan Tengah']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Barito Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Palangkaraya']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Barito Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Barito Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Gunung Mas']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kapuas']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Katingan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kotawaringin Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kotawaringin Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lamandau']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Murung Raya']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pulang Pisau']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Seruyan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sukamara']);
        $province = Province::create(['province_name'=>'Kalimantan Selatan']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Balangan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Banjarmasin']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Banjar']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Banjar Baru']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Barito Kuala']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Hulu Sungai Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Hulu Sungai Tengah']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Hulu Sungai Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kotabaru']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tabalong']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tanah Bumbu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tanah Laut']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tapin']);
        $province = Province::create(['province_name'=>'Gorontalo']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Boalemo']); 
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Gorontalo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bone Bolango']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Gorontalo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Gorontalo Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pohuwato']);
        $province = Province::create(['province_name'=>'Sulawesi Selatan']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Selayar']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Makasar']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bantaeng']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Pare-Pare']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Barru']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Palopo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bone']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bulukumba']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Enrekang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Gowa']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Jeneponto']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Luwu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Luwu Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Luwu Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Maros']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pangkep']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pinrang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sidenreng Rappang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sinjai']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Soppeng']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Takalar']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tanatoraja']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Wajo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Toraja Utara']);
        $province = Province::create(['province_name'=>'Sulawesi Tenggara']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bombana']); 
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Kendari']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Buton']); 
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Bau-Bau']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Konawe (dulu: Kab. Kendari)']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kolaka']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kolaka Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Konawe Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Muna']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Wakatobi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Konawe Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Buton Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kolaka Timur']);
        $province = Province::create(['province_name'=>'Sulawesi Tengah']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Banggai']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Palu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Banggai Kepulauan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Buol']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Donggala']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Morowali']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Parigi Mountong']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Poso']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tojo Una-Una']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Toli-Toli']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sigi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Banggai Laut']);
        $province = Province::create(['province_name'=>'Sulawesi Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bolaang Mongondow']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Manado']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bolaang Mongondow Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Kotamobagu']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Minahasa']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Bitung']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Minahasa Tenggara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Tomohon']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Minahasa Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Minahasa Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sangihe Talaud']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kep. Talaud']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kep. Siau Tagulandang Biaro']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bolaang Mongondow Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Bolaang Mongondow Selatan']);
        $province = Province::create(['province_name'=>'Sulawesi Barat']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Mamuju']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Majene']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Mamuju Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Mamasa']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Polewali Mamasa']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Mamuju Tengah']);
        $province = Province::create(['province_name'=>'Maluku']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Buru']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Ambon']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kepulauan Aru']); 
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Tual']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Seram Bagian Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Seram Bagian Timur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Maluku Tengah']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Maluku Tenggara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Maluku Tenggara Barat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Maluku Barat Daya']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Buru Selatan']);
        $province = Province::create(['province_name'=>'Maluku Utara']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Halmahera Barat']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Ternate']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Halmahera Selatan']); 
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Tidore Kepulauan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Halmahera Tengah']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Halmahera Tirnur']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab Halmahera Utara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kepulauan Sula']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Morotai']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pulau Taliabu']);
        $province = Province::create(['province_name'=>'Papua']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Asmat']); 
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Jayapura']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Biak Numfor']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Boven Digoel']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Jayapura']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Jayawijaya']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Keerom']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Mappi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Merauke']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Mimika']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Paniai']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pegunungan Bintang']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Puncak Jaya']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sarmi']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Mamberamo Raya']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Supiori']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tolikara']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Yahukimo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Yapen Waropen']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Waropen']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Nabire']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Mamberamo Tengah']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Yalimo']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Lanny Jaya']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Nduga']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Puncak']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Dogiyai']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Deiyai']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Intan Jaya']);
        $province = Province::create(['province_name'=>'Papua Barat']);
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Fak-Fak']); 
        	City::create(['province_id'=>$province->id, 'cities_name'=>'Kota Sorong']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kaimana']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Kepulauan Raja Ampat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Manokwari']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sorong Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Teluk Bintuni']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Sorong']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Teluk Wondama']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Tambrauw']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Maybrat']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Manokwari Selatan']);
			City::create(['province_id'=>$province->id, 'cities_name'=>'Kab. Pegunungan Arfak']);
    }
}